# Generated by Django 6.0.4 on 2026-05-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва команди')),
                ('score', models.IntegerField(default=0, verbose_name='Бали')),
                ('is_online', models.BooleanField(default=False, verbose_name='Статус')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Блок')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField(default=0, verbose_name='Ціна поточного питання')),
                ('is_buzzer_active', models.BooleanField(default=False, verbose_name='Активність кнопки')),
                ('buzzer_locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.team', verbose_name='Хто відповідає')),
            ],
        ),
    ]
