# Generated by Django 6.0.4 on 2026-05-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='has_buzzed',
            field=models.BooleanField(default=False, verbose_name='Натиснута кнопка'),
        ),
    ]
